name: preprint-review-metadata
title: null
theme: just-the-docs

# Enable GitHub edit links
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/elifesciences/preprint-review-metadata"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
