name: preprint-review-metadata
title: null
theme: just-the-docs

defaults:
  - scope:
      path: "preprint-review-metadata/docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
